Add a new COMContext object in AppInstaller Core to enable COM Interface to consume AppInstaller
microsoft/winget-cli pull request #818
Opened 2021-03-25 22:19 UTC by sachintaMSFT

Add a new COMContext object in AppInstaller Core to enable COM Interface to issue any commands to AppInstaller. The COM Context object will also enable COM Interface to see the progress, receive errors and cancel execution of commands, where applicable.

2021-03-25 22:36 UTC, sachintaMSFT commented
> #### Misspellings found, please review:
> * streambuf
> 
> To accept these changes, run the following commands from this repository on this branch

will add streambuf word to .github/actions/spelling/expect.txt in alphabetical sort order along in the commit for incorporation of any review comments received.

2021-03-26 16:43 UTC, JohnMcPMS commented
/azp run

2021-03-26 21:16 UTC, JohnMcPMS requested changes

2021-03-26 21:16 UTC, JohnMcPMS commented on src/AppInstallerCLICore/Public/AppInstallerCLICoreExecute.h
> +    int Execute(Execution::Context& context, std::unique_ptr<Command>& command);
Assuming that the plan is to implement the COM interface classes in another static lib (I support that plan), then many other headers will "need" to be placed in public.  I think it makes sense for Command and Context to be made public, and then COMContext will actually be moved over to that lib.

This function should then be in Command.h, and the "make this command" function should be too.

For now, COMContext can live where you have it in this PR, but at least move this function to Command.h.

2021-03-26 21:16 UTC, JohnMcPMS commented on src/AppInstallerCLICore/Core.cpp
> +    int Execute(Execution::Context& context, std::unique_ptr<Command>& command)
RE: my other comment, move this to Command.cpp.

2021-03-26 21:16 UTC, JohnMcPMS commented on src/AppInstallerCLICore/ExecutionContext.h
> +        virtual void SetExecutionStage(Workflow::ExecutionStage stage);
No need to separate these functions, but if you are going to do so, the virtual function should be protected.

2021-03-26 21:16 UTC, JohnMcPMS commented on src/AppInstallerCLITests/TestCommon.cpp
> +        _Unreferenced_parameter_(hideProgressWhenDone);
Remove name from signature.

2021-03-26 23:56 UTC, sachintaMSFT commented on src/AppInstallerCLICore/COMContext.cpp
> +        m_comProgressCallback(ReportType::BeginProgress, m_current, m_maximum, m_type, m_executionPhase);
I do reset progress values in SetExecutionStage. But I guess if there are multiple separate & sequential progresses in same ExecutionStage (which I think Discover stage has), that doesn't help BeginProgress send reset progress values. And if that progress is super quick that OnProgress isn't called and EndProgress get called directly, then the leak goes into EndProgress as well. Accept your suggestion.

2021-03-27 00:33 UTC, sachintaMSFT commented
/azp run

2021-03-27 00:37 UTC, JohnMcPMS commented
/azp run

2021-03-27 00:50 UTC, JohnMcPMS approved these changes

2021-03-27 15:48 UTC, merged